# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_compute <- function(nn, covariate_in, dropout, visible_dropout, hidden_dropout) {
    .Call('HGTools_c_compute', PACKAGE = 'HGTools', nn, covariate_in, dropout, visible_dropout, hidden_dropout)
}

c_compute_bm <- function(nn, covariate_in) {
    .Call('HGTools_c_compute_bm', PACKAGE = 'HGTools', nn, covariate_in)
}

c_generate_initial_variables <- function(data, model_list, act_fct, err_fct) {
    .Call('HGTools_c_generate_initial_variables', PACKAGE = 'HGTools', data, model_list, act_fct, err_fct)
}

c_calculate_neuralnet <- function(data, model_list, hidden, stepmax, rep, threshold, learningrate_limit, learningrate_factor, lifesign, covariate, response, lifesign_step, startweights, algorithm, act_fct, act_deriv_fct, act_fct_name, err_fct, err_deriv_fct, err_fct_name, linear_output, likelihood, exclude, constant_weights, learningrate_bp, dropout, visible_dropout, hidden_dropout) {
    .Call('HGTools_c_calculate_neuralnet', PACKAGE = 'HGTools', data, model_list, hidden, stepmax, rep, threshold, learningrate_limit, learningrate_factor, lifesign, covariate, response, lifesign_step, startweights, algorithm, act_fct, act_deriv_fct, act_fct_name, err_fct, err_deriv_fct, err_fct_name, linear_output, likelihood, exclude, constant_weights, learningrate_bp, dropout, visible_dropout, hidden_dropout)
}

c_generate_initial_variables_bm <- function(data, covariate_bm, response_bm, model_list, act_fct, err_fct) {
    .Call('HGTools_c_generate_initial_variables_bm', PACKAGE = 'HGTools', data, covariate_bm, response_bm, model_list, act_fct, err_fct)
}

c_calculate_neuralnet_bm <- function(data, model_list, hidden, stepmax, rep, threshold, learningrate_limit, learningrate_factor, lifesign, covariate, response, lifesign_step, startweights, algorithm, act_fct, act_deriv_fct, act_fct_name, err_fct, err_deriv_fct, err_fct_name, linear_output, likelihood, exclude, constant_weights, learningrate_bp, dropout, visible_dropout, hidden_dropout) {
    .Call('HGTools_c_calculate_neuralnet_bm', PACKAGE = 'HGTools', data, model_list, hidden, stepmax, rep, threshold, learningrate_limit, learningrate_factor, lifesign, covariate, response, lifesign_step, startweights, algorithm, act_fct, act_deriv_fct, act_fct_name, err_fct, err_deriv_fct, err_fct_name, linear_output, likelihood, exclude, constant_weights, learningrate_bp, dropout, visible_dropout, hidden_dropout)
}

